name: Build with Batch Script

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run build.bat
      shell: cmd
      run: |
        build.bat

    - name: Upload executable
      uses: actions/upload-artifact@v3
      with:
        name: built-executable
        path: dist/*.exe
